{% set name = "momepy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bc99a56854e760674996865d2c48e3686a5d9a45efe29c5aca64e58c557b8f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas
    - networkx
    - libpysal
    - tqdm
    - gdal >=2.4

test:
  imports:
    - momepy

about:
  home: http://momepy.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Urban Morphology Measuring Toolkit for Python

  description: |
    Momepy is a project allowing advanced quantitative analysis of urban morphology.
    Embracing principles of Urban Morphometrics, this toolkit aims to provide tools
    for the development of complex frameworks for a description of urban structures.
  doc_url: http://docs.momepy.org
  dev_url: https://github.com/martinfleis/momepy

extra:
  recipe-maintainers:
    - martinfleis
