{% set name = "momepy" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7b62de1ee420518491ce3cd2bc21815a149cc2a5e6132f122486e8542a74248

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - geopandas >=0.12.0
    - libpysal >=4.12.0
    - networkx >=2.8
    - packaging
    - pandas >=1.5.1
    - shapely >=2
    - tqdm >=4.63.0

test:
  imports:
    - momepy
  requires:
    - python {{ python_min }}

about:
  home: http://momepy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Urban Morphology Measuring Toolkit for Python

  description: |
    Momepy is a project allowing advanced quantitative analysis of urban morphology.
    Embracing principles of Urban Morphometrics, this toolkit aims to provide tools
    for the development of complex frameworks for a description of urban structures.
  doc_url: http://docs.momepy.org
  dev_url: https://github.com/pysal/momepy

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
