travis:
  secure:
    BINSTAR_TOKEN: Xxgkh+P9OwEwP6DvmeCBs+BUhW4MZ3ffGf4fcpa3cv70yaOISTvkF5erEQmJe7r7/KJcnk1jwbQbLGNLnMgG97m8xY3s7udjWpQwXcjd4gllOwHRBCeQfJ+BnqQuj0OyBkCx7458D3aB8tbVG4M7CyOwwYjHOBKTCSNgczsy1TsO0llk181E6p1lve61wCCMs6i+aWDMx7JuCXqGuDkKKThIC5If2gxcbl7zTd9paXdxWe1JrkjmIUnTRhO6dQ+iLPvEJAH0XZ2DgGhbzqNDezjmqR/ce1a3L9M6bM4mtIy+bOjiZWzsUXwe0Kuqn9vww3FbvJUyPwCtEDFOetBgvgfUArEuY6QCzianazzZjDSMwD97dM2Se9cYiArqdzOsLLVVXvxEAauvIuxDzSc99xqOSX8nk5MyluFZiW13eNlTeuOSYh9zMKcRG8skNM0q01g+SgoZM/Sf5OkASSwSOtxYIcubY+2LDr/hU0f4KrhtLYbUJXiuDfZnOmBVZQeX70pg9tqo/bDuYgqFy44y1zDcPEiFVXpz/ti6osm8WSAf1RCxwjWi+9AtPJSTL8eIiTtfxKUgrstcerFSWoUbcJeZaWUXVU99KKRSFZ8ao+DOMaNyQ2NC9W9dO0AKrlc7pretbCJXd5fg3liQ5daETC09/L1VEcTm4yYjf2vEiWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
